### ISSUE TITLE
Change access

### ISSUE THREAD

**Issue by Soyrce** [rivit98/AMXX_Plugins#1]
Can you do me a favor and make it just VIP? With NATIVE?
get_user_vip ? abd.sma

**Comment by rivit98** [comment]
Please create a new topic here: https://amxx.pl/forum/39-multilingual/
Remember to attach .sma.

**Comment by Soyrce** [comment]
> Please create a new topic here: https://amxx.pl/forum/39-multilingual/
> Remember to attach .sma.

https://amxx.pl/topic/165056-abd-access-native/
